image: archlinux
packages:
  - rust
sources:
  - https://git.sr.ht/~wahn/rs-pbrt
tasks:
  - cargo-version: |
      cargo --version
  - test: |
      cd rs-pbrt
      cargo test --release --no-default-features
  - help_parse_blend_file: |
      cd rs-pbrt
      cargo run --bin parse_blend_file --release --no-default-features -- --help
  - help_rs_pbrt: |
      cd rs-pbrt
      cargo run --bin rs_pbrt --release --no-default-features -- --help
